--EXAM
SELECT SUBSTR(EMAIL,INSTR(EMAIL,'@')+1) "DOMAIN"
     , COUNT(EMAIL) "EA"
     , (SELECT COUNT(*) FROM PROFESSOR) "SUM_DOMAIN"
     , ROUND(COUNT(EMAIL)/(SELECT COUNT(*) FROM PROFESSOR)*100,2) "%"
  FROM PROFESSOR 
 GROUP BY SUBSTR(EMAIL,INSTR(EMAIL,'@')+1)
 ORDER BY 1;